// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnLmKaM83lBlx8bgnUcaHsmoAkCEhng34',
    appId: '1:1040350791871:web:69a27909c729cedb329e0a',
    messagingSenderId: '1040350791871',
    projectId: 'fp-flutter-c37f5',
    authDomain: 'fp-flutter-c37f5.firebaseapp.com',
    storageBucket: 'fp-flutter-c37f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOxiEiSo0D2MpTen-mdb6IPR-z903Qjc',
    appId: '1:1040350791871:android:3c4298ea5a932256329e0a',
    messagingSenderId: '1040350791871',
    projectId: 'fp-flutter-c37f5',
    storageBucket: 'fp-flutter-c37f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8lEEnksRardGUqWaDez_LGOe-qh18_Sg',
    appId: '1:1040350791871:ios:db9861273b268454329e0a',
    messagingSenderId: '1040350791871',
    projectId: 'fp-flutter-c37f5',
    storageBucket: 'fp-flutter-c37f5.appspot.com',
    iosBundleId: 'com.example.fpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8lEEnksRardGUqWaDez_LGOe-qh18_Sg',
    appId: '1:1040350791871:ios:db9861273b268454329e0a',
    messagingSenderId: '1040350791871',
    projectId: 'fp-flutter-c37f5',
    storageBucket: 'fp-flutter-c37f5.appspot.com',
    iosBundleId: 'com.example.fpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnLmKaM83lBlx8bgnUcaHsmoAkCEhng34',
    appId: '1:1040350791871:web:30b56a2531eb96ed329e0a',
    messagingSenderId: '1040350791871',
    projectId: 'fp-flutter-c37f5',
    authDomain: 'fp-flutter-c37f5.firebaseapp.com',
    storageBucket: 'fp-flutter-c37f5.appspot.com',
  );

}